import { createElement } from 'lwc';
import Createnewaccountlwc from 'c/createnewaccountlwc';
const mockGetRecord = require("./data/getRecordMock.json");
import { getRecord } from "lightning/uiRecordApi";

describe('c-createnewaccountlwc', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-createnewaccountlwc', {
            is: Createnewaccountlwc
        });
        document.body.appendChild(element);
        const div = element.shadowRoot.querySelector('div');
        expect(div.textContent).toBe('Hello, World!');
    });

    it("Test Account Get Record", () => {
        const element = createElement('c-createnewaccountlwc', {
            is: Createnewaccountlwc
        });
        document.body.appendChild(element);
        getRecord.emit(mockGetRecord);

        return Promise.resolve().then(() => {
            const content = element.shadowRoot.querySelector(".name");
            const nameField = mockGetRecord.fields.Name.value;
            expect(content.textContent).toBe(`Name:${nameField}`);
        });
    })
});